import type { Metadata } from "next";
import { Satisfy } from "next/font/google";

import "./globals.css";

const satisfy = Satisfy({weight: ["400"], subsets: ["latin"]});


export const metadata: Metadata = {
  title: "Escape from the Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satisfy.className}`}
      >
        {children}
      </body>
    </html>
  );
}
